[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "/plugins/netlify-plugin-stepzen"

[template]
  incoming-hooks = ["StepZen"]

[template.environment]
  NEXT_PUBLIC_STEPZEN_API_KEY = "Add your StepZen admin key"
  NEXT_PUBLIC_STEPZEN_ACCOUNT = "Add your StepZen account name"
