[build]
  command = "npm build"
  publish = "public"

[[plugins]]
  package = "/plugins/netlify-plugin-stepzen"

[template]
  incoming-hooks = ["StepZen"]

[template.environment]
  NEXT_PUBLIC_STEPZEN_URI = "Add your StepZen account name"
  NEXT_PUBLIC_STEPZEN_API_KEY = "Add your StepZen admin key"
